services:
  - type: web
    name: chitgit-server
    env: python
    rootDir: Server
    buildCommand: pip install -r requirement.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker main:app --bind 0.0.0.0:$PORT --workers 1
