[supervisord]
nodaemon=true

[program:api]
command=uvicorn main:app --host 0.0.0.0 --port 10000
autostart=true
autorestart=true

[program:worker]
command=rq worker default \ --url "rediss://default:gQAAAAAAARIgAAIgcDI1ZDU3M2E2MGEzOWE0MmJmYjA3YjE4NTAyODNkNmI2Ng@leading-goblin-70176.upstash.io:6379" \ -worker-class rq.worker.SimpleWorker
autostart=true
autorestart=true